ROIIM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('users.urls')),
    path('', include('checkout.urls')),
    path('admin/', admin.site.urls),
]

checkout/urls.py
from django.urls import path
from . import views

app_name = 'checkout'
urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('payment_successful/', views.payment_successful, name='payment_successful')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('', views.signin, name='user_login'),
    path('logout/', views.signout, name='user_logout'),
]

checkout/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

users/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')

class CheckoutForm(forms.Form):
    amount = forms.IntegerField()

    class Meta():
        fields = ['amount']

checkout/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render


# Create your views here.

@login_required
def checkout(request):
    username = request.user.username
    user = User.objects.get(username=username)
    print(username, user.first_name, user.last_name, user.email)
    context = {
        'total_amount': 100,
        'first_name': user.first_name,
        'last_name': user.last_name,
        'email': user.email
    }
    return render(request, 'checkout.html', context)

@login_required
def payment_successful(request):
    return render(request, 'payment_successful.html')

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from users.forms import UserForm, CheckoutForm


def dashboard(request):
    if request.method == 'POST':
        checkout_form = CheckoutForm(request.POST)
        if checkout_form.is_valid():
            amount = checkout_form.cleaned_data['amount']
            print('amount....', amount)
            return render(request, 'checkout.html', {'amount': amount})
    return render(request, 'dashboard.html')


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
            return redirect('user:user_login')
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()

    return render(request, 'register.html', {'user_form': user_form, 'registered': registered})

def signin(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect('checkout:checkout')
            else:
                return HttpResponse('Your account is not active')
        return render(request, 'signin.html')
    else:
        return render(request, 'signin.html')


@login_required
def signout(request):
    logout(request)
    return redirect('user:user_login')

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css"
            href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css">
        <title>
            {% block title %}{% endblock %}
        </title>
        <style>
            .errorlist{
                color: red;
            }
            .completed{
                background-color : rgba(7, 243, 7, 0.356) !important;
            }
            .expired{
                background-color : rgba(255, 0, 0, 0.507) !important;
            }
        </style>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-dark bg-dark">
            <div class="col-md-10">
                <a class="navbar-brand" href="{% url 'checkout:checkout' %}">Checkout</a>
            </div>
            <div class="col-md-1">
                <a href="{% url 'user:user_logout' %}">Logout</a>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
    </body>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js" integrity="sha384-XEerZL0cuoUbHE4nZReLT7nx9gQrQreJekYhJD9WNWhH8nEW+0c5qq7aIo2Wl30J" crossorigin="anonymous"></script>
    <script type="text/javascript" charset="utf8"
        src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js"></script>

</html>

templates/checkout.html
{% extends 'dashboard.html' %}

{% block content %}

    <script src="https://hosted.paysafe.com/checkout/v2/paysafe.checkout.min.js"></script>

        <div class="container">
            <div class="jumbotron">

        {% if user.is_authenticated %}
            <h4>Please Pay</h4>

            <div>
                <button onclick="checkout()"> Pay ${{ total_amount }}</button>
            </div>


        {% else %}
            <h1>Welcome to the ROIIM!</h1>

        {% endif %}
            </div>
        </div>


    <script>
        function checkout() {

            var api = "cHVibGljLTc3NTE6Qi1xYTItMC01ZjAzMWNiZS0wLTMwMmQwMjE1MDA4OTBlZjI2MjI5NjU2M2FjY2QxY2I0YWFiNzkwMzIzZDJmZDU3MGQzMDIxNDUxMGJjZGFjZGFhNGYwM2Y1OTQ3N2VlZjEzZjJhZjVhZDEzZTMwNDQ="
            paysafe.checkout.setup(api, {
                "currency": "USD",
                "amount": {{total_amount}}00,
                "locale": "en_US",
                "customer": {
                    "firstName": "{{first_name}}",
                    "lastName": "{{last_name}}",
                    "email": "{{email}}",
                    "phone": "1234567890",
                    "dateOfBirth": {
                        "day": 1,
                        "month": 7,
                        "year": 1990
                    }
                },
                "billingAddress": {
                    "nickName": "{{first_name}} {{last_name}}",
                    "street": "20735 Stevens Creek Blvd",
                    "street2": "Montessori",
                    "city": "Cupertino",
                    "zip": "95014",
                    "country": "US",
                    "state": "CA"
                },
                "environment": "TEST",
                "merchantRefNum": "149900597607",
                "canEditAmount": true,
                "merchantDescriptor": {
                    "dynamicDescriptor": "XYZ",
                    "phone": "1234567890"
                    },
                "displayPaymentMethods":["skrill","card"],
                "paymentMethodDetails": {
                    "paysafecard": {
                        "consumerId": "1232323"
                    },
                    "paysafecash": {
                        "consumerId": "123456"
                    },
                    "sightline": {
                        "consumerId": "123456",
                        "SSN": "123456789",
                        "last4ssn": "6789",
                        "accountId":"1009688222"
                    },
                    "vippreferred":{
                        "consumerId": "550726575",
                        "accountId":"1679688456"
                    }
                }
            }, function(instance, error, result) {
                if (result && result.paymentHandleToken) {
                    console.log(result.paymentHandleToken);
                    // make AJAX call to Payments API

                    var request = new XMLHttpRequest();

                    request.open('POST', 'https://private-anon-bda7caa8f0-paysafeapipaymenthubv1.apiary-mock.com/paymenthub/v1/payments', true);

                    request.setRequestHeader('Content-Type', 'application/json');
                    request.setRequestHeader('Authorization', 'cHJpdmF0ZS03NzUxOkItcWEyLTAtNWYwMzFjZGQtMC0zMDJkMDIxNDQ5NmJlODQ3MzJhMDFmNjkwMjY4ZDNiOGViNzJlNWI4Y2NmOTRlMjIwMjE1MDA4NTkxMzExN2YyZTFhODUzMTUwNWVlOGNjZmM4ZTk4ZGYzY2YxNzQ4Cg==');
                    request.setRequestHeader('Simulator', '"INTERNAL"');

                    request.onreadystatechange = function () {
                    if (this.readyState === 4) {
                        console.log('Status:', this.status);
                        console.log('Headers:', this.getAllResponseHeaders());
                        console.log('Body:', this.responseText);
                    }
                    };

                    var body = {
                    'merchantRefNum': '1559900597607',
                    'amount': {{ total_amount }},
                    'currencyCode': 'USD',
                    'dupCheck': true,
                    'settleWithAuth': true,
                    'paymentHandleToken': result.paymentHandleToken,
                    'customerIp': '10.10.12.64',
                    'description': 'Magazine subscription'
                    };

                    request.send(JSON.stringify(body));
                    window.open('/payment_successful');

                } else {
                    console.error(error);
                    // Handle the error
                }
            }, function(stage, expired) {
                switch(stage) {
                    case "PAYMENT_HANDLE_NOT_CREATED": // Handle the scenario
                    case "PAYMENT_HANDLE_CREATED": // Handle the scenario
                    case "PAYMENT_HANDLE_REDIRECT": // Handle the scenario
                    case "PAYMENT_HANDLE_PAYABLE": // Handle the scenario
                    default: // Handle the scenario
                }
            });
        }
    </script>


{% endblock %}

templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST" action="{% url 'checkout:checkout' %}">
    {% csrf_token %}
        <p style="margin:10px 10px auto">Enter Amount</p>
{#        {{ checkout_form.as_p }}#}
        <input type="number" id="amount" name="amount" placeholder="enter amount" value="{{ form_amount }}" style="margin:10px 10px auto"> <br>
        <input type="submit" name="submit" value="Checkout" style="margin:10px 10px auto" class="btn btn-primary" onclick="{% url 'checkout:checkout' %}">
    </form>
{% endblock %}

templates/payment_successful.html
<!DOCTYPE html>
<html lang="en">
    <h>Payment Sucessful</h><br><br>
    <form form action="/checkout/", method="GET">
        <button type="submit">
            Return to shopping window
        </button>
    </form>
</html>>

templates/register.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
        <title>
            Register User
        </title>
        <style>
            .errorlist{
                color: red;
            }
            .completed{
                background-color : rgba(7, 243, 7, 0.356) !important;
            }
            .expired{
                background-color : rgba(255, 0, 0, 0.507) !important;
            }
        </style>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-dark bg-dark">
            <div class="col-md-10">
                <a class="navbar-brand" href="">Register here</a>
            </div>
        </nav>
        <br>
        <form action="" method="post">

            {% csrf_token %}
            <fieldset class="form-group">
                {{ user_form.as_p }}
            </fieldset>

            <button type="reset" class="btn btn-secondary" required style="margin:10px 10px auto">Reset</button>

            <button type="submit" class="btn btn-primary" required style="margin:10px 10px auto">Register</button>
        </form>
    </body>
</html>

templates/signin.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
        <title>
            Login | User
        </title>
        <style>
            .errorlist{
                color: red;
            }
            .completed{
                background-color : rgba(7, 243, 7, 0.356) !important;
            }
            .expired{
                background-color : rgba(255, 0, 0, 0.507) !important;
            }
            .successfulMsg{
                color : blue;
                font-size: 1.5rem;
            }
        </style>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-dark bg-dark">
            <div class="col-md-10">
                <a class="navbar-brand" href="">Login Page</a>
            </div>
        </nav>
        <br>
        {% if messages %}
            {% for message in messages %}
                <p class="successfulMsg">{{ message }}</p>
            {% endfor %}
        {% endif %}
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <p style="margin:10px 10px auto">Username</p>
            <input type="text" name="username" id="Username" placeholder="Enter Username" required style="margin:10px 10px auto">
            <p style="margin:10px 10px auto">Password</p>
            <input type="password" name="password" id="Password" placeholder="Enter Password" required style="margin:10px 10px auto"><br>
            <button class="btn btn-primary" style="margin: 10px 10px auto;">Login</button>
            <p>
                <span style="padding: 0 0.5%">
                    <a href="#">Forgot Password</a>
                </span>
                <span style="padding: 0 0.5%">
                    <a href="{% url 'user:register' %}">Register</a>
                </span>
            </p>
        </form>
    </body>
</html>